[TS-244] Added activities route
TradeShare490/TradeShare-BE pull request #25
Opened 2022-01-06 09:36 UTC by tungleu

added endpoint to get recent activities 
`GET /actitivities/:userId`
![image](https://user-images.githubusercontent.com/30036024/148361840-ac0ab1e9-9554-45b2-802a-73934f649615.png)

2022-01-07 17:26 UTC, bowe99 requested changes

2022-01-07 17:26 UTC, bowe99 commented on src/controllers/activities.controller.ts
> +		let account = {};
This should be renamed to activities

2022-01-07 17:26 UTC, bowe99 commented on src/controllers/activities.controller.ts
> +		res.send(messages.internalError("User hasn't linked any Alpaca account"));
This code is failing Sonar because of duplication maybe you can clean it up a little

2022-01-07 17:33 UTC, bowe99 requested changes

2022-01-07 17:33 UTC, bowe99 commented on src/routes/v1/activities.route.ts
> +import requireUser from "../../middleware/requireUser";
This is not being used you can remove it

2022-01-15 20:21 UTC, kennguyen0303 requested changes
Great work, only 2 small things you might have known. I think having `await` and `return` is necessary. Although there might be no issue on your method, it triggers unexpected behavior sometimes if you work on a different feature. 

Food for thoughts: `await` will tell NodeJS to mark that line, run that function in synchronous behavior and wait for a return; As a result, if your workflow contains only one method, it won't make any difference. Without `await`, nodejs will jump over your call without waiting for the return/response, possibly go to the next lines of code (if there any).

Thanks @bowe99 for noticing the unused imports, I would have missed them for sure.

2022-01-15 20:21 UTC, kennguyen0303 commented on src/db/service/alpaca.service.ts
> +			return res.send(messages.successMessage("success", infoType, alpacaInfo));
```suggestion
			const {data}= await axios.get(endPoint, {
				headers: { Authorization: `Bearer ` + alpacaToken },
			});
			return res.send(messages.successMessage("success", infoType, data));
```

Save you one line and one variable

2022-01-15 20:21 UTC, kennguyen0303 commented on src/controllers/positions.controller.ts
> +			return this.alpacaService.getInfo(req, res, "/positions", "positions", userInfo.alpacaToken);
```suggestion
			return await this.alpacaService.getInfo(req, res, "/positions", "positions", userInfo.alpacaToken);
```

missing `await`

2022-01-15 20:21 UTC, kennguyen0303 commented on src/controllers/positions.controller.ts
> +			res.send(messages.internalError("User hasn't linked any Alpaca account"));
```suggestion
			return res.send(messages.internalError("User hasn't linked any Alpaca account"));
```

Missing `return` for convention

2022-01-15 20:21 UTC, kennguyen0303 commented on src/controllers/activities.controller.ts
> +			return this.alpacaService.getInfo(
```suggestion
			return await this.alpacaService.getInfo(
```

missing `await`

2022-01-15 20:21 UTC, kennguyen0303 commented on src/controllers/account.controller.ts
> +			res.send(messages.internalError("User hasn't linked any Alpaca account"));
```suggestion
			return res.send(messages.internalError("User hasn't linked any Alpaca account"));
```

missing `return`

2022-01-15 20:21 UTC, kennguyen0303 commented on src/controllers/account.controller.ts
> +			return this.alpacaService.getInfo(req, res, "/account", "account", userInfo.alpacaToken);
```suggestion
			return await this.alpacaService.getInfo(req, res, "/account", "account", userInfo.alpacaToken);
```

missing `await`

2022-01-15 20:55 UTC, kennguyen0303 reviewed
I would like to have a unit test for the service before this is merged. Will it be possible?

2022-01-16 03:01 UTC, kennguyen0303 submitted a review, later dismissed
lgtm!

2022-01-16 04:25 UTC, kennguyen0303 approved these changes

2022-01-17 22:52 UTC, kennguyen0303 commented
@bowe99 need your review here since you requested some changes.

2022-01-18 02:45 UTC, kennguyen0303 approved these changes

2022-01-21 04:10 UTC, GadoliniumPotassium approved these changes

2022-01-21 19:13 UTC, merged