[TS-282] Re-integrate username
TradeShare490/TradeShare-BE pull request #27
Opened 2022-01-16 07:31 UTC by tungleu

username is required in signup and user can sign-in either by email or username 
![image](https://user-images.githubusercontent.com/30036024/149651298-7b03c181-bf15-4794-9bdf-76cd4cb58b1b.png)

2022-01-17 21:48 UTC, GadoliniumPotassium commented
Looks good to me, coding conventions are followed and the code works.I  didn't find a problem with it but someone else might find a way to break it. good job.

2022-01-17 22:22 UTC, GadoliniumPotassium submitted a review, later dismissed

2022-01-17 22:59 UTC, kennguyen0303 requested changes
Code seems okay. Yet, looking for a test for searching/getting by username

2022-01-17 22:59 UTC, kennguyen0303 commented on src/db/service/user.service.ts
> +	async validatePassword(body: any) {
There is no test for getting/searching by username yet. Can you add at least one so that we know it is working?

2022-01-18 04:44 UTC, kennguyen0303 approved these changes

2022-01-19 04:23 UTC, GadoliniumPotassium approved these changes
LGTM!

2022-01-19 04:24 UTC, merged