Ts 207
TradeShare490/TradeShare-BE pull request #47
Opened 2022-03-13 22:59 UTC by GadoliniumPotassium

2022-03-13 23:10 UTC, GadoliniumPotassium commented
Can this be tested and merged so I can call this in the front end and finish my reset password PR

2022-03-14 03:26 UTC, kennguyen0303 requested changes
Looking good. Just need to

- [x] Verify the input in controller
- [x] register the route to the routeRegister

2022-03-14 03:26 UTC, kennguyen0303 commented on src/utils/email/MailController.ts
> +            const mail = this.emailService.send(req.body);
We should verify the format of `req.body` to ensure all inputs suffice

2022-03-14 03:26 UTC, kennguyen0303 commented on src/utils/email/MailController.ts
> +            return messages.successMessage('success','sentMail',mail)
Need to add `res.send(..)` to send the response to the client. If you don't need to send anything to the client, don't return a value.

```suggestion
            return res.send(messages.successMessage('success','sentMail',mail))
```

2022-03-17 01:18 UTC, tungleu approved these changes

2022-03-18 17:02 UTC, tungleu approved these changes

2022-03-18 17:05 UTC, kennguyen0303 approved these changes

2022-03-18 17:07 UTC, merged